let allData = [
  {"universitas": ["Akademi Komunitas Negeri Aceh Barat", "AKADEMI KOMUNITAS NEGERI ACEH BARAT DAYA", "AKN", "AKN Aceh Barat", "AKN Aceh Barat Daya"],
  "dosen": []},
  {"universitas": ["Institut Seni dan Budaya Indonesia Aceh", "ISBI", "ISBI Aceh"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Lhokseumawe", "PNL"],
  "dosen": []},
  {"universitas": ["Universitas Syiah Kuala", "Unsyiah"],
  "dosen": []},
  {"universitas": ["Universitas Malikussaleh", "UNIMAL"],
  "dosen": []},
  {"universitas": ["Universitas Samudra", "UNSAM"],
  "dosen": []},
  {"universitas": ["Universitas Teuku Umar", "UTU"],
  "dosen": []},
  {"universitas": ["Universitas Sumatera Utara", "USU"],
  "dosen": []},
  {"universitas": ["Universitas Negeri Medan", "UNIMED"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Medan", "Politeknik Universitas Sumatera Utara" ,"Politeknik USU"],
  "dosen": []},
  {"universitas": ["Universitas Andalas", "Unand"],
  "dosen": []},
  {"universitas": ["Universitas Negeri Padang", "UNP"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Andalas", "Politeknik Andalas", "Politeknik Negeri Padang", "Politeknik Universitas Andalas"],
  "dosen": []},
  {"universitas": ["Politeknik Pertanian Negeri Payakumbuh"],
  "dosen": []},
  {"universitas": ["Institut Seni Indonesia Padang Panjang", "STSI"],
  "dosen": []},
  {"universitas": ["Universitas Riau", "UR"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Bengkalis", "POLBENG"],
  "dosen": []},
  {"universitas": ["Universitas Maritim Raja Ali Haji", "UMRAH"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Batam"],
  "dosen": []},
  {"universitas": ["Universitas Jambi", "UNJA"],
  "dosen": []},
  {"universitas": ["Universitas Bengkulu"],
  "dosen": []},
  {"universitas": ["Universitas Sriwijaya", "UNSRI"],
  "dosen": []},
  {"universitas": ["Akademi Komunitas Negeri (AKN) Banyuasin", "AKN", "AKN Banyuasin"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Sriwijaya"],
  "dosen": []},
  {"universitas": ["Universitas Lampung", "Unila"],
  "dosen": []},
  {"universitas": ["Institut Teknologi Sumatera", "ITERA"],
  "dosen": []},
  {"universitas": ["Politeknik Negeri Lampung"],
  "dosen": []},
  {"universitas": ["Universitas Bangka Belitung", "UBB"],
  "dosen": []},
  {"universitas": ["Politeknik Manufaktur Negeri Bangka Belitung"],
  "dosen": []},
  {"universitas": ["Universitas Bina Nusantara", "Binus", "Binus University"],
  "dosen": ["Lili Ayu Wulandhari", "Widodo Budiharto"]}
];
